### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'underscore_numbers'

### ISSUE THREAD

**Issue by Violating** [MPCodeWriter21/whois21#1]
![image](https://user-images.githubusercontent.com/71596309/203451614-5490dd8d-ad44-4bde-bac5-4283bd512fc6.png)

Any help? followed your examples step-by step- and installed without issue, giving me this error.

**Comment by MPCodeWriter21** [comment]
Hi! 
Thank you for your report. 
This is a problem in `log21.pformat` function that raises this error in Python versions lower than 3.10.
I will fix it in a few days then you can update the package and use it as expected or if you are in a hurry you can upgrade your python now.

**Comment by MPCodeWriter21** [comment]
The new version is out now!
```shell
python3 -m pip install whois21 -U
```
Please let me know if you find any other bugs/errors.
