### ISSUE TITLE
TypeError: fromisoformat: argument must be str

### ISSUE THREAD

**Issue by arkanoid87** [MPCodeWriter21/whois21#5]
python 3.11.5
whois21==1.4.2

```
whois21/__init__.py", line 334, in parse_time
```

**Comment by MPCodeWriter21** [comment]
Hi @arkanoid87!

Thank you for testing out whois21 and for reporting this issue. I appreciate your help in making the package better. To assist you further, it would be very helpful if you could provide the complete traceback of the error, outline the steps you followed to encounter it and maybe mention your operating system. This will allow me to understand the issue more comprehensively.

Rest assured, I'm committed to resolving this as soon as I get chance to do so.

Looking forward to your additional details, and thank you for your patience as I work to address this problem.

**Comment by MPCodeWriter21** [comment]
Hello there! 👋

I've just finished working on a fix for this issue and have released whois21 version 1.4.3 with some minor changes. Please update your package to the latest version and let me know if it resolves the problem you reported.

Your feedback and reports are invaluable in improving whois21. Thank you for your support and for helping us make the package better!

**Comment by arkanoid87** [comment]
I'm sorry, I just realized that the issue text content I was expecting to find is way shorter than expected, not sure how this happened, it looks truncated to me and I didn't realize it immediately.

Props for spotting the issue even without details!

**Comment by MPCodeWriter21** [comment]
No problem at all! It happens to the best of us. I'm just glad we were able to identify the issue and work towards a solution. If you encounter any further issues or have any questions, please don't hesitate to reach out. Your feedback is highly valuable to us, and I'm here to assist you with anything related to whois21. Thank you for your understanding and support!

**Comment by arkanoid87** [comment]
Surely the most professional answers to the least professional request ever
